server:
  port: 8761

spring:
  application:
    name: eureka-server
  zipkin:
#    instead of localhost the docker service's container_name
    base-url: http://zipkin:9411

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
